-- nvim-dap: Debug Adapter Protocol client for Neovim
-- Provides LLDB-DAP integration for iOS/macOS debugging with Bazel projects.
-- This is the Neovim equivalent of the VSCode lldb-dap extension.
return {
	{
		"mfussenegger/nvim-dap",
		dependencies = {
			"rcarriga/nvim-dap-ui",
			"nvim-neotest/nvim-nio",
		},
		keys = {
			{ "<leader>db", function() require("dap").toggle_breakpoint() end, desc = "Toggle breakpoint" },
			{ "<leader>dB", function() require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: ")) end, desc = "Conditional breakpoint" },
			{ "<leader>dc", function() require("dap").continue() end, desc = "Continue" },
			{ "<leader>di", function() require("dap").step_into() end, desc = "Step into" },
			{ "<leader>do", function() require("dap").step_over() end, desc = "Step over" },
			{ "<leader>dO", function() require("dap").step_out() end, desc = "Step out" },
			{ "<leader>dr", function() require("dap").repl.toggle() end, desc = "Toggle REPL" },
			{ "<leader>dl", function() require("dap").run_last() end, desc = "Run last" },
			{ "<leader>dt", function() require("dap").terminate() end, desc = "Terminate" },
			{ "<leader>du", function() require("dapui").toggle() end, desc = "Toggle DAP UI" },
			-- iOS-specific: launch full build+debug cycle
			{ "<leader>dI", function() require("ios").debug() end, desc = "iOS: Build & Debug" },
		},
		config = function()
			local dap = require("dap")
			local dapui = require("dapui")

			dapui.setup({
				layouts = {
					{
						elements = {
							{ id = "scopes", size = 0.35 },
							{ id = "breakpoints", size = 0.15 },
							{ id = "stacks", size = 0.25 },
							{ id = "watches", size = 0.25 },
						},
						position = "left",
						size = 40,
					},
					{
						elements = {
							{ id = "repl", size = 0.5 },
							{ id = "console", size = 0.5 },
						},
						position = "bottom",
						size = 10,
					},
				},
			})

			-- Auto open/close DAP UI
			dap.listeners.after.event_initialized["dapui_config"] = function()
				dapui.open()
			end
			dap.listeners.before.event_terminated["dapui_config"] = function()
				dapui.close()
			end
			dap.listeners.before.event_exited["dapui_config"] = function()
				dapui.close()
			end

			-- lldb-dap adapter configuration
			-- lldb-dap is shipped with the Swift toolchain (Xcode) or can be
			-- installed separately. It is the same adapter used by the VSCode
			-- LLDB-DAP extension.
			local lldb_dap_path = vim.env.LLDB_DAP_PATH or "lldb-dap"

			dap.adapters["lldb-dap"] = {
				type = "executable",
				command = lldb_dap_path,
				name = "lldb-dap",
			}

			-- Swift / iOS attach configuration
			-- This mirrors the VSCode launch.json "attach" configuration from
			-- sourcekit-bazel-bsp's Example project. The actual PID and LLDB
			-- commands come from the ios.lua workflow module.
			dap.configurations.swift = {
				{
					name = "iOS: Attach to running app",
					type = "lldb-dap",
					request = "attach",
					pid = function()
						-- Read PID from the launch info file generated by
						-- lldb_launch_and_debug.sh
						local cwd = vim.fn.getcwd()
						local lldb_json = cwd .. "/.bsp/skbsp_generated/lldb.json"
						local f = io.open(lldb_json, "r")
						if not f then
							vim.notify("No lldb.json found. Run iOS build+launch first.", vim.log.levels.ERROR)
							return nil
						end
						local content = f:read("*a")
						f:close()
						local info = vim.json.decode(content)
						return info.pid
					end,
					-- Source mapping: map Bazel execution root paths back to workspace
					initCommands = function()
						local cwd = vim.fn.getcwd()
						local bazel_json = cwd .. "/.bsp/skbsp_generated/bazel_info.json"
						local cmds = {}
						local f = io.open(bazel_json, "r")
						if f then
							local content = f:read("*a")
							f:close()
							local info = vim.json.decode(content)
							local output_base = info.output_base or ""
							local execution_root = info.execution_root or ""
							-- Set CWD to execution root so relative archive paths work
							table.insert(cmds, string.format('platform settings -w "%s"', execution_root))
							-- Map source paths from exec root to workspace
							table.insert(cmds, string.format('settings append target.source-map "." "%s"', cwd))
							table.insert(cmds, string.format(
								'settings insert-before target.source-map 0 "./external/" "%s/external/"',
								output_base
							))
						end
						-- Prevent lldb timeout on large projects
						table.insert(cmds, "settings set plugin.process.gdb-remote.packet-timeout 300")
						return cmds
					end,
					stopOnEntry = false,
					waitFor = true,
				},
			}

			-- Also apply the swift configurations to objc/objcpp
			dap.configurations.objc = dap.configurations.swift
			dap.configurations.objcpp = dap.configurations.swift

			-- Breakpoint signs
			vim.fn.sign_define("DapBreakpoint", { text = "B", texthl = "DiagnosticError", linehl = "", numhl = "" })
			vim.fn.sign_define("DapBreakpointCondition", { text = "C", texthl = "DiagnosticWarn", linehl = "", numhl = "" })
			vim.fn.sign_define("DapStopped", { text = ">", texthl = "DiagnosticOk", linehl = "DapStoppedLine", numhl = "" })

			-- Highlight for the stopped line
			vim.api.nvim_set_hl(0, "DapStoppedLine", { bg = "#2e4d3d" })
		end,
	},
}
